---
driver:
  name: vagrant
  network:
    - ["private_network", { ip: "192.168.36.37" }]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[chef-cookbook-wrapper-wordpress::default]
    attributes:
